### ISSUE TITLE
pinMode( ), why do we set pin 8 and 10 to output?

### ISSUE THREAD

**Issue by indiesquidge** [CSCI-4830-002-2014/project-1-make-a#2]
When we use pinMode( ), why do we set pin 8 and 10 to output? I didn't think we used either of those pins, unless I'm not understanding what is referred to as a "pin".

**Comment by wannabeCitizen** [comment]
We set those to output so that we guarantee both are on and being sent voltage by arduino's internal supply. If one of those doesn't turn on the SD doesn't turn on so this is just a guarantee.
